Worker for circulating supply calculation
cheqd/cosmos-data-api pull request #1
Opened 2022-04-05 14:26 UTC by askolesov

2022-04-05 14:26 UTC, ankurdotb commented
Task linked: [DEV-1028 Create API to report circulating supply](https://app.clickup.com/t/6600954/DEV-1028)

2022-04-05 14:29 UTC, askolesov commented
Worker: https://dash.cloudflare.com/99b9572de9d3c33774965949416b82c9/workers/services/view/query-circulating-supply/dev

Once the PR is merged, we can provide the worker to the prod workspace.
Also, we need to update `deny_list` properly.

2022-04-14 10:09 UTC, ankurdotb requested changes

2022-04-14 10:09 UTC, ankurdotb commented on workers/query_circulating_supply/README.md
> +```
So you're setting this as a KV pair with one Key and all of the addresses as values? I'd suggest switching this to using wallet address as key and the value entry could be something like maybe the timestamp in epoch when it was added. The rationale is that in case something needs to be added/removed, especially if for testing/removing we want to do it from Cloudflare GUI, keeping the addresses as a key is a much better way to do it. Value can even be text rather than JSON and you're not really using the value at all, and can be hard-coded when there's a bulk upload done.

Also this KV Pair will be separate from the airdrop denylist. The contents might be very similar, but the lists aren't exactly the same.

2022-04-14 10:09 UTC, ankurdotb commented on workers/query_circulating_supply/worker.js
> +const BIG_DIPPER_GRAPHQL_URL = "https://explorer-gql.cheqd.io/v1/graphql";
Do check CORS settings and firewall rules in Cloudflare to see if this traffic is allowed through.

2022-05-11 14:53 UTC, askolesov commented on workers/query_circulating_supply/README.md
> +```
> So you're setting this as a KV pair with one Key and all of the addresses as values?

Not, actually. I use environment variable `DENY_LIST` and json array as its value.

2022-05-11 14:57 UTC, askolesov commented on workers/query_circulating_supply/README.md
> +```
> I'd suggest switching this to using wallet address as key and the value entry could be something like maybe the timestamp in epoch when it was added. The rationale is that in case something needs to be added/removed, especially if for testing/removing we want to do it from Cloudflare GUI, keeping the addresses as a key is a much better way to do it.

IMO It's easier to update a single ENV variable then maintaining a set of KV pairs per each address (as I remember we expect hundreds of addresses). Would you agree?

2022-05-11 15:02 UTC, askolesov commented on workers/query_circulating_supply/worker.js
> +const BIG_DIPPER_GRAPHQL_URL = "https://explorer-gql.cheqd.io/v1/graphql";
It works in the dev deployment: https://dev.query-circulating-supply.cheqd.workers.dev/

2022-05-11 15:06 UTC, askolesov commented
@ankurdotb Thanks for the review. Posted answers to your comments. Can we do a quick call? Looks like it will be the fastest way to reach a consensus.

2022-05-12 16:10 UTC, ankurdotb commented on workers/query_circulating_supply/worker.js
> +  let non_circulating_addresses = JSON.parse(DENY_LIST);
As discussed, let's swap over to KV pairs: cheqd wallet address is the key, value (defined when bulk upload is done via Wrangler or added via dashboard).

2022-05-20 09:15 UTC, ankurdotb requested changes

2022-05-20 09:15 UTC, ankurdotb commented on src/query_circulating_supply/worker.js
> +const BIG_DIPPER_GRAPHQL_URL = "https://explorer-gql.cheqd.io/v1/graphql";
Set in a config file or environment variable file? This can be in wrangler.toml if I recall the syntax.

2022-05-20 17:29 UTC, ankurdotb requested changes
We need to figure out why deploys are failing

2022-05-23 12:36 UTC, askolesov commented on .github/workflows/deploy.yml
> +          apiToken: ${{ secrets.CF_API_TOKEN }}
If a project is simple enough, wrangler 2.0 builds it automatically. I'm able to push worker to Cloudflare with the config above and my token. So most probably the issue is in tokens that are in GitHub.

2022-05-23 12:37 UTC, askolesov commented on package.json
> +  "version": "0.0.0",
Whoops, good catch!

2022-05-23 12:38 UTC, askolesov commented on src/index.ts
> + */
Outdated

2022-05-23 12:39 UTC, askolesov commented on src/query_circulating_supply/worker.js
> +const BIG_DIPPER_GRAPHQL_URL = "https://explorer-gql.cheqd.io/v1/graphql";
Exactly. This is one more thing that is left.

2022-05-23 12:42 UTC, askolesov commented
TODOs for whoever picks this up:
* Move most of the constants from `constants.ts` to `wrangler.toml` as environment variables;
* Make circulating supply endpoint to read `deny list` (need a new name for this) to read config from KV pairs.

2022-05-24 18:15 UTC, Eengineer1 commented on src/helpers/node.ts
> +        .map(a => parseInt(a.amount))
Same

2022-05-24 18:15 UTC, Eengineer1 commented on src/helpers/node.ts
> +        .map(a => parseInt(a.amount))
Same

2022-05-24 19:40 UTC, ankurdotb commented on .github/workflows/deploy.yml
> +          node-version: '16.x'
Since this is on Cloudflare and it's a relatively new platform I'm happy to stick to just current LTS (16.x) wherever possible. Only if an upstream needs an older Node.js should we bother to do this for compatibility purposes.

2022-05-24 20:06 UTC, ankurdotb approved these changes

2022-05-24 20:07 UTC, merged